# Generated by Django 5.2.14 on 2026-05-29 00:16

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0064_alter_league_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "Applied"),
                    (7, "Invitation Pending"),
                    (2, "Invited"),
                    (3, "Confirmed"),
                    (4, "Declined"),
                    (10, "Assignment Pending"),
                    (8, "Assigned"),
                    (9, "Rejection Pending"),
                    (5, "Rejected"),
                    (6, "Withdrawn"),
                ],
                default=1,
            ),
        ),
    ]
